CREATE TABLE
  public.courses (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name character varying NULL,
    description text NULL,
    image character varying NULL
  );

ALTER TABLE
  public.courses
ADD
  CONSTRAINT courses_pkey PRIMARY KEY (id)